name: Merge me test dependencies!

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Run linters'
      - 'Run tests'
      - 'Run tests on macos'
      - 'Test build package'
  check_suite:
    types:
     - completed

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@5e3ff7b4d544d6b3b8336cdc9c029cff9ab7abb3 # v5.2.7
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
