name: Merge me test dependencies!

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Run linters'
      - 'Run tests'
      - 'Run tests on macos'
      - 'Test build package'

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@f35c0eab43b88cb5f67a8519eb6dea27146f2145 # v5.2.4
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
