name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@f35c0eab43b88cb5f67a8519eb6dea27146f2145 # v5.2.4
