name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@f35c0eab43b88cb5f67a8519eb6dea27146f2145 # v5.2.4
    with:
      dependency-manager: 'uv'
