name: Run pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    uses: fizyk/actions-reuse/.github/workflows/shared-pre-commit.yml@c76d10cf9448b3a9afdbef29e727e0fd00b2f544 # v5.2.8
