name: Run pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    uses: fizyk/actions-reuse/.github/workflows/shared-pre-commit.yml@31be9bf07155154cfce850e9d4133b502ee6f023 # v5.3.0
