name: Package and publish
on:
  push:
    tags:
      - v*



jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@a77b9a9554742fe1ad70b0c0cd589235fd0a60fb # v5.2.1
    with:
      publish: true
    secrets:
      pypi_token: ${{ secrets.pypi_password }}
