name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to be added'
        required: true
        type: string

jobs:
  release:
    uses: fizyk/actions-reuse/.github/workflows/shared-release.yml@9328bd2621a0322c2d7aeb80cd41f53a8771f4ee # v5.2.5
    with:
      version: ${{ inputs.version }}
    secrets:
      app_id: ${{ secrets.RELEASE_APP_ID }}
      private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
