name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@67c2d834b83f6a05dd0d398d20d21b79f062d7fa # v5.2.2
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy-3.11"]'
      dependency-manager: 'uv'
      pytest_opts: '-n auto --dist loadgroup'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  macostests:
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@67c2d834b83f6a05dd0d398d20d21b79f062d7fa # v5.2.2
    needs: [tests]
    with:
      python-versions: '["3.12", "3.13", "3.14", "3.15", "pypy-3.11"]'
      dependency-manager: 'uv'
      pytest_opts: '-n auto --dist loadgroup --basetemp=$RUNNER_TEMP/pt'
      os: macos-14 # macos-latest is on macos-15 which misbehaves'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  oldest:
    needs: [tests]
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy-3.11"]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up UV on python ${{ matrix.python-version }}
        uses: fizyk/actions-reuse/.github/actions/uv-setup@a77b9a9554742fe1ad70b0c0cd589235fd0a60fb # v5.2.1
        with:
          python-version: ${{ matrix.python-version }}
          cache: false
      - name: Install oldest supported versions
        uses: fizyk/actions-reuse/.github/actions/uv-run@a77b9a9554742fe1ad70b0c0cd589235fd0a60fb # v5.2.1
        with:
          command: pip install -r oldest-requirements.rq
      - name: Run tests
        uses: fizyk/actions-reuse/.github/actions/uv-run@a77b9a9554742fe1ad70b0c0cd589235fd0a60fb # v5.2.1
        with:
          command: pytest -v --cov --cov-report=xml -n auto --dist loadgroup
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: false
